import type { Metadata } from "next";
import { Belleza, EB_Garamond, Geist } from "next/font/google";
import "./globals.css";
import PreLoader from "@/components/loader/Preloader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const garamond = EB_Garamond({
  variable: "--font-garamond",
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "500", "600", "700"],
});

const belleza = Belleza({
  variable: "--font-belleza",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${garamond.variable} ${belleza.variable} h-full antialiased`}
    >
      <body className="min-h-svh flex flex-col">
        <PreLoader />
        <main className="min-h-full flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
